contact_links:
  - name: Feature request
    url: https://github.com/orgs/khulnasoft/discussions/categories/khulnasoft
    about: Propose an enhancement at discussions.
  - name: Support
    url: https://khulnasoft.com/support/
    about: Professional support for the open source innovation.
